  enum NodeType
{	ADD_NODE,SUB_NODE,MULT_NODE,DIVIDE_NODE,GT_NODE,GTE_NODE,LT_NODE,LTE_NODE,
	EQUAL_NODE,NOT_EQUAL_NODE,function_NODE,
	FUNCRETURN_NODE,IF_NODE,CONDITION_NODE,ELSE_NODE,BLOCK_NODE,PRINT_NODE
};

struct Node{   
	NodeType Type;
	int      Value;
};
