  enum NodeType
{
    LINE, BLOCK, STATEMENT_LIST, IF_ELSE_STATEMENT,
    TYPE, IF_STATEMENT, ASSIGNMENT_STATEMENT,NAME_State,
	 OPERATOR, WRITE_STATEMENT, NEWLINE_STATEMENT,
    CONDITIONAL, CONDITION, EXPRESSION, VALUE, COMPARATOR, CONSTANT,ADD,SUBTRACK,MULT,DIVIDE
};


struct Node{   
  NodeType Type;
   int      Value;
   Node*    Left;
   Node*    Right;
};